# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=15, verbose_name='ativo')),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Fisica'), ('J', 'Juridica')], max_length=15, verbose_name='tipo')),
            ],
            options={
                'ordering': ['ativo', 'tipo_pessoa'],
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=40, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa', verbose_name='pessoa')),
            ],
            options={
                'ordering': ['pessoa', 'nomeCompleto', 'cpf'],
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=11, unique=True, verbose_name='Cnpj')),
                ('site', models.CharField(max_length=20, verbose_name='Site')),
                ('nomeFantasia', models.CharField(max_length=20, verbose_name='NomeFantasia')),
                ('razaoSocial', models.CharField(max_length=20, verbose_name='RazaoSocial')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa', verbose_name='pessoa')),
            ],
            options={
                'ordering': ['cnpj', 'nomeFantasia'],
            },
        ),
    ]
